version: 0.1.{build}
image: Ubuntu
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: false
build_script:
- ps: ./build.ps1
deploy_script:
- ps: ./build.ps1 Pack -NugetVersionPrefix '0.1.$env:APPVEYOR_BUILD_NUMBER'  -NugetVersionSuffix alpha